#!/bin/sh

# Xcode Cloud post-clone step.
#
# Downbar's Xcode project is generated by XcodeGen from project.yml and is
# gitignored (see .gitignore), so the cloned repo has no .xcodeproj. Generate it
# here, before Xcode Cloud resolves the scheme and builds.
#
# Runs in the Xcode Cloud environment immediately after the repo is cloned.

set -e

echo "ci_post_clone: ensuring XcodeGen is installed"
if ! command -v xcodegen >/dev/null 2>&1; then
  brew install xcodegen
fi

echo "ci_post_clone: generating Downbar.xcodeproj from project.yml"
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

echo "ci_post_clone: done"
